#!/usr/bin/env python3
# Auto-generated by generate_bindings.py
import ctypes
import os

# Load Library
_lib_path = os.path.join(os.path.dirname(__file__), '../build/bin/libriengine.so')
try:
    _lib = ctypes.CDLL(_lib_path)
except OSError:
    # Fallback to local fallback or error
    try:
        _lib = ctypes.CDLL('libriengine.so')
    except OSError:
        print(f'Using mock library for {_lib_path}')
        _lib = None

# Constants
# BHS_LIB_MATH_BHS_MATH_H = #ifndef BHS_SHADER_COMPILER # Complex definition
# BHS_GPU_KERNEL = #define BHS_DEVICE_FUNC # Complex definition
# BHS_DEVICE_FUNC = #define BHS_ALIGN(x) __attribute__((aligned(x))) # Complex definition
# BHS_EPSILON = 1e-9 # Complex definition
# bhs_abs = fabs # Complex definition
# bhs_sqrt = sqrt # Complex definition
# bhs_pow = pow # Complex definition
# bhs_sin = sin # Complex definition
# bhs_cos = cos # Complex definition
# bhs_tan = tan # Complex definition
# bhs_acos = acos # Complex definition
# bhs_atan2 = atan2 # Complex definition
M_PI = 3.14159265358979323846
# BHS_CORE_MATH_VEC4_H = #include <stdbool.h> # Complex definition
# BHS_LIB_ECS_H = #include <stdbool.h> # Complex definition
BHS_ENTITY_INVALID = 0
BHS_MAX_ENTITIES = 10000
# BHS_CORE_ASSERT_H = #include <stdio.h> # Complex definition
# BHS_CORE_TENSOR_TENSOR_H = #include <stdbool.h> # Complex definition
# BHS_CORE_SPACETIME_KERR_H = #include "math/tensor/tensor.h" # Complex definition
# BHS_CORE_SPACETIME_SCHWARZSCHILD_H = #include "math/tensor/tensor.h" # Complex definition
# BHS_CORE_LIB_H = #include "math/bhs_math_assert.h" # Complex definition
# BHS_ENGINE_H = #include "math/core.h" # Complex definition
# BHS_ENGINE_DATA_SUN_H = #include "math/vec4.h" # Complex definition
# BHS_ENGINE_DATA_BLACKHOLE_H = #include "math/vec4.h" # Complex definition
# BHS_ENGINE_SCENE_NEW_H = typedef struct bhs_scene_impl *bhs_scene_t; # Complex definition
BHS_MAX_TRAIL_POINTS = 65536
# BHS_TYPES_H = #include "math/vec4.h" # Complex definition

# Enums
# enum bhs_sun_stage
BHS_SUN_MAIN_SEQUENCE = 0
BHS_SUN_RED_GIANT = 1
BHS_SUN_WHITE_DWARF = 2
BHS_SUN_NEUTRON_STAR = 3
# enum bhs_body_type
BHS_BODY_PLANET = 0
BHS_BODY_MOON = 1
BHS_BODY_STAR = 2
BHS_BODY_BLACKHOLE = 3
BHS_BODY_ASTEROID = 4
# enum bhs_matter_state
BHS_STATE_SOLID = 0
BHS_STATE_LIQUID = 1
BHS_STATE_GAS = 2
BHS_STATE_PLASMA = 3
# enum bhs_shape_type
BHS_SHAPE_SPHERE = 0
BHS_SHAPE_ELLIPSOID = 1
BHS_SHAPE_IRREGULAR = 2
# enum bhs_star_stage
BHS_STAR_MAIN_SEQUENCE = 0
BHS_STAR_GIANT = 1
BHS_STAR_WHITE_DWARF = 2
BHS_STAR_NEUTRON = 3

# Opaque Handles
class bhs_world_handle(ctypes.Structure):
    pass
class bhs_scene_t(ctypes.Structure):
    pass

# Forward Declarations
class bhs_vec4(ctypes.Structure):
    pass
class bhs_vec3(ctypes.Structure):
    pass
class bhs_metric(ctypes.Structure):
    pass
class bhs_christoffel(ctypes.Structure):
    pass
class bhs_kerr(ctypes.Structure):
    pass
class bhs_schwarzschild(ctypes.Structure):
    pass
class bhs_sun_desc(ctypes.Structure):
    pass
class bhs_blackhole_desc(ctypes.Structure):
    pass
class bhs_planet_data(ctypes.Structure):
    pass
class bhs_star_data(ctypes.Structure):
    pass
class bhs_blackhole_data(ctypes.Structure):
    pass
class bhs_body_state(ctypes.Structure):
    pass
class bhs_body_u_prop(ctypes.Structure):
    pass
class bhs_body(ctypes.Structure):
    pass
class bhs_body_u_prop(ctypes.Union):
    pass

# bhs_body_u_prop definition
bhs_body_u_prop._fields_ = [
        ('planet', bhs_planet_data),
        ('star', bhs_star_data),
        ('bh', bhs_blackhole_data),
    ]

# Struct Definitions
# bhs_vec4 definition
bhs_vec4._fields_ = [
        ('t', ctypes.c_double),
        ('x', ctypes.c_double),
        ('y', ctypes.c_double),
        ('z', ctypes.c_double),
    ]

# bhs_vec3 definition
bhs_vec3._fields_ = [
        ('x', ctypes.c_double),
        ('y', ctypes.c_double),
        ('z', ctypes.c_double),
    ]

# bhs_metric definition
bhs_metric._fields_ = [
        ('g', ('BHS_ALIGN(16) real_t' * 4)),
    ]

# bhs_christoffel definition
bhs_christoffel._fields_ = [
        ('gamma', ('BHS_ALIGN(16) real_t' * 4)),
    ]

# bhs_kerr definition
bhs_kerr._fields_ = [
        ('M', ctypes.c_double),
        ('a', ctypes.c_double),
    ]

# bhs_schwarzschild definition
bhs_schwarzschild._fields_ = [
        ('M', ctypes.c_double),
    ]

# bhs_sun_desc definition
bhs_sun_desc._fields_ = [
        ('name', ctypes.POINTER('const char')),
        ('mass', ctypes.c_double),
        ('radius', ctypes.c_double),
        ('temperature', ctypes.c_double),
        ('luminosity', ctypes.c_double),
        ('age', ctypes.c_double),
        ('metallicity', ctypes.c_double),
        ('stage', ctypes.c_int),
        ('spectral_type', (ctypes.c_char * 8)),
        ('rotation_period', ctypes.c_double),
        ('axis_tilt', ctypes.c_double),
        ('base_color', bhs_vec3),
        ('p_local)', bhs_vec3),
    ]

# bhs_blackhole_desc definition
bhs_blackhole_desc._fields_ = [
        ('name', ctypes.POINTER('const char')),
        ('mass', ctypes.c_double),
        ('spin', ctypes.c_double),
        ('charge', ctypes.c_double),
        ('event_horizon_r', ctypes.c_double),
        ('accretion_disk_mass', ctypes.c_double),
        ('base_color', bhs_vec3),
        ('p_local)', bhs_vec3),
    ]

# bhs_planet_data definition
bhs_planet_data._fields_ = [
        ('density', ctypes.c_double),
        ('axis_tilt', ctypes.c_double),
        ('rotation_period', ctypes.c_double),
        ('j2', ctypes.c_double),
        ('albedo', ctypes.c_double),
        ('has_atmosphere', ctypes.c_bool),
        ('surface_pressure', ctypes.c_double),
        ('atmosphere_mass', ctypes.c_double),
        ('composition', (ctypes.c_char * 64)),
        ('temperature', ctypes.c_double),
        ('heat_capacity', ctypes.c_double),
        ('energy_flux', ctypes.c_double),
        ('physical_state', ctypes.c_int),
        ('has_magnetic_field', ctypes.c_bool),
    ]

# bhs_star_data definition
bhs_star_data._fields_ = [
        ('luminosity', ctypes.c_double),
        ('temp_effective', ctypes.c_double),
        ('age', ctypes.c_double),
        ('density', ctypes.c_double),
        ('hydrogen_frac', ctypes.c_double),
        ('helium_frac', ctypes.c_double),
        ('metals_frac', ctypes.c_double),
        ('stage', ctypes.c_int),
        ('metallicity', ctypes.c_double),
        ('spectral_type', (ctypes.c_char * 8)),
    ]

# bhs_blackhole_data definition
bhs_blackhole_data._fields_ = [
        ('spin_factor', ctypes.c_double),
        ('event_horizon_r', ctypes.c_double),
        ('ergososphere_r', ctypes.c_double),
        ('accretion_disk_mass', ctypes.c_double),
        ('accretion_rate', ctypes.c_double),
    ]

# bhs_body_state definition
bhs_body_state._fields_ = [
        ('pos', bhs_vec3),
        ('vel', bhs_vec3),
        ('acc', bhs_vec3),
        ('rot_axis', bhs_vec3),
        ('rot_speed', ctypes.c_double),
        ('moment_inertia', ctypes.c_double),
        ('mass', ctypes.c_double),
        ('radius', ctypes.c_double),
        ('current_rotation_angle', ctypes.c_double),
        ('shape', ctypes.c_int),
    ]

# bhs_body_u_prop definition
bhs_body_u_prop._fields_ = [
        ('planet', bhs_planet_data),
        ('star', bhs_star_data),
        ('bh', bhs_blackhole_data),
    ]

# bhs_body definition
bhs_body._fields_ = [
        ('state', bhs_body_state),
        ('type', ctypes.c_int),
        ('prop', 'bhs_body_u_prop'),
        ('color', bhs_vec3),
        ('is_fixed', ctypes.c_bool),
        ('is_alive', ctypes.c_bool),
        ('name', (ctypes.c_char * 32)),
        ('trail_positions', (ctypes.c_float * 65536)),
        ('trail_head', ctypes.c_int),
        ('trail_count', ctypes.c_int),
    ]

# Functions
if _lib:
    # bhs_vec4 bhs_vec4_add
    if hasattr(_lib, 'bhs_vec4_add'):
        bhs_vec4_add = _lib.bhs_vec4_add
        bhs_vec4_add.argtypes = [bhs_vec4, bhs_vec4]
        bhs_vec4_add.restype = 'bhs_vec4'
    else:
        print(f'Warning: Function bhs_vec4_add not found in library')
    # bhs_vec4 bhs_vec4_sub
    if hasattr(_lib, 'bhs_vec4_sub'):
        bhs_vec4_sub = _lib.bhs_vec4_sub
        bhs_vec4_sub.argtypes = [bhs_vec4, bhs_vec4]
        bhs_vec4_sub.restype = 'bhs_vec4'
    else:
        print(f'Warning: Function bhs_vec4_sub not found in library')
    # bhs_vec4 bhs_vec4_scale
    if hasattr(_lib, 'bhs_vec4_scale'):
        bhs_vec4_scale = _lib.bhs_vec4_scale
        bhs_vec4_scale.argtypes = [bhs_vec4, ctypes.c_double]
        bhs_vec4_scale.restype = 'bhs_vec4'
    else:
        print(f'Warning: Function bhs_vec4_scale not found in library')
    # bhs_vec4 bhs_vec4_neg
    if hasattr(_lib, 'bhs_vec4_neg'):
        bhs_vec4_neg = _lib.bhs_vec4_neg
        bhs_vec4_neg.argtypes = [bhs_vec4]
        bhs_vec4_neg.restype = 'bhs_vec4'
    else:
        print(f'Warning: Function bhs_vec4_neg not found in library')
    # real_t bhs_vec4_dot_minkowski
    if hasattr(_lib, 'bhs_vec4_dot_minkowski'):
        bhs_vec4_dot_minkowski = _lib.bhs_vec4_dot_minkowski
        bhs_vec4_dot_minkowski.argtypes = [bhs_vec4, bhs_vec4]
        bhs_vec4_dot_minkowski.restype = ctypes.c_double
    else:
        print(f'Warning: Function bhs_vec4_dot_minkowski not found in library')
    # real_t bhs_vec4_norm2_minkowski
    if hasattr(_lib, 'bhs_vec4_norm2_minkowski'):
        bhs_vec4_norm2_minkowski = _lib.bhs_vec4_norm2_minkowski
        bhs_vec4_norm2_minkowski.argtypes = [bhs_vec4]
        bhs_vec4_norm2_minkowski.restype = ctypes.c_double
    else:
        print(f'Warning: Function bhs_vec4_norm2_minkowski not found in library')
    # bool bhs_vec4_is_null
    if hasattr(_lib, 'bhs_vec4_is_null'):
        bhs_vec4_is_null = _lib.bhs_vec4_is_null
        bhs_vec4_is_null.argtypes = [bhs_vec4, ctypes.c_double]
        bhs_vec4_is_null.restype = ctypes.c_bool
    else:
        print(f'Warning: Function bhs_vec4_is_null not found in library')
    # bool bhs_vec4_is_timelike
    if hasattr(_lib, 'bhs_vec4_is_timelike'):
        bhs_vec4_is_timelike = _lib.bhs_vec4_is_timelike
        bhs_vec4_is_timelike.argtypes = [bhs_vec4]
        bhs_vec4_is_timelike.restype = ctypes.c_bool
    else:
        print(f'Warning: Function bhs_vec4_is_timelike not found in library')
    # bool bhs_vec4_is_spacelike
    if hasattr(_lib, 'bhs_vec4_is_spacelike'):
        bhs_vec4_is_spacelike = _lib.bhs_vec4_is_spacelike
        bhs_vec4_is_spacelike.argtypes = [bhs_vec4]
        bhs_vec4_is_spacelike.restype = ctypes.c_bool
    else:
        print(f'Warning: Function bhs_vec4_is_spacelike not found in library')
    # bhs_vec3 bhs_vec3_add
    if hasattr(_lib, 'bhs_vec3_add'):
        bhs_vec3_add = _lib.bhs_vec3_add
        bhs_vec3_add.argtypes = [bhs_vec3, bhs_vec3]
        bhs_vec3_add.restype = 'bhs_vec3'
    else:
        print(f'Warning: Function bhs_vec3_add not found in library')
    # bhs_vec3 bhs_vec3_sub
    if hasattr(_lib, 'bhs_vec3_sub'):
        bhs_vec3_sub = _lib.bhs_vec3_sub
        bhs_vec3_sub.argtypes = [bhs_vec3, bhs_vec3]
        bhs_vec3_sub.restype = 'bhs_vec3'
    else:
        print(f'Warning: Function bhs_vec3_sub not found in library')
    # bhs_vec3 bhs_vec3_scale
    if hasattr(_lib, 'bhs_vec3_scale'):
        bhs_vec3_scale = _lib.bhs_vec3_scale
        bhs_vec3_scale.argtypes = [bhs_vec3, ctypes.c_double]
        bhs_vec3_scale.restype = 'bhs_vec3'
    else:
        print(f'Warning: Function bhs_vec3_scale not found in library')
    # real_t bhs_vec3_dot
    if hasattr(_lib, 'bhs_vec3_dot'):
        bhs_vec3_dot = _lib.bhs_vec3_dot
        bhs_vec3_dot.argtypes = [bhs_vec3, bhs_vec3]
        bhs_vec3_dot.restype = ctypes.c_double
    else:
        print(f'Warning: Function bhs_vec3_dot not found in library')
    # bhs_vec3 bhs_vec3_cross
    if hasattr(_lib, 'bhs_vec3_cross'):
        bhs_vec3_cross = _lib.bhs_vec3_cross
        bhs_vec3_cross.argtypes = [bhs_vec3, bhs_vec3]
        bhs_vec3_cross.restype = 'bhs_vec3'
    else:
        print(f'Warning: Function bhs_vec3_cross not found in library')
    # real_t bhs_vec3_norm
    if hasattr(_lib, 'bhs_vec3_norm'):
        bhs_vec3_norm = _lib.bhs_vec3_norm
        bhs_vec3_norm.argtypes = [bhs_vec3]
        bhs_vec3_norm.restype = ctypes.c_double
    else:
        print(f'Warning: Function bhs_vec3_norm not found in library')
    # real_t bhs_vec3_norm2
    if hasattr(_lib, 'bhs_vec3_norm2'):
        bhs_vec3_norm2 = _lib.bhs_vec3_norm2
        bhs_vec3_norm2.argtypes = [bhs_vec3]
        bhs_vec3_norm2.restype = ctypes.c_double
    else:
        print(f'Warning: Function bhs_vec3_norm2 not found in library')
    # bhs_vec3 bhs_vec3_normalize
    if hasattr(_lib, 'bhs_vec3_normalize'):
        bhs_vec3_normalize = _lib.bhs_vec3_normalize
        bhs_vec3_normalize.argtypes = [bhs_vec3]
        bhs_vec3_normalize.restype = 'bhs_vec3'
    else:
        print(f'Warning: Function bhs_vec3_normalize not found in library')
    # void bhs_vec3_to_spherical
    if hasattr(_lib, 'bhs_vec3_to_spherical'):
        bhs_vec3_to_spherical = _lib.bhs_vec3_to_spherical
        bhs_vec3_to_spherical.argtypes = [bhs_vec3, ctypes.POINTER(ctypes.c_double), ctypes.POINTER(ctypes.c_double), ctypes.POINTER(ctypes.c_double)]
        bhs_vec3_to_spherical.restype = None
    else:
        print(f'Warning: Function bhs_vec3_to_spherical not found in library')
    # bhs_vec3 bhs_vec3_from_spherical
    if hasattr(_lib, 'bhs_vec3_from_spherical'):
        bhs_vec3_from_spherical = _lib.bhs_vec3_from_spherical
        bhs_vec3_from_spherical.argtypes = [ctypes.c_double, ctypes.c_double, ctypes.c_double]
        bhs_vec3_from_spherical.restype = 'bhs_vec3'
    else:
        print(f'Warning: Function bhs_vec3_from_spherical not found in library')
    # bhs_world_handle bhs_ecs_create_world
    if hasattr(_lib, 'bhs_ecs_create_world'):
        bhs_ecs_create_world = _lib.bhs_ecs_create_world
        bhs_ecs_create_world.argtypes = []
        bhs_ecs_create_world.restype = ctypes.c_void_p
    else:
        print(f'Warning: Function bhs_ecs_create_world not found in library')
    # void bhs_ecs_destroy_world
    if hasattr(_lib, 'bhs_ecs_destroy_world'):
        bhs_ecs_destroy_world = _lib.bhs_ecs_destroy_world
        bhs_ecs_destroy_world.argtypes = [ctypes.c_void_p]
        bhs_ecs_destroy_world.restype = None
    else:
        print(f'Warning: Function bhs_ecs_destroy_world not found in library')
    # bhs_entity_id bhs_ecs_create_entity
    if hasattr(_lib, 'bhs_ecs_create_entity'):
        bhs_ecs_create_entity = _lib.bhs_ecs_create_entity
        bhs_ecs_create_entity.argtypes = [ctypes.c_void_p]
        bhs_ecs_create_entity.restype = 'bhs_entity_id'
    else:
        print(f'Warning: Function bhs_ecs_create_entity not found in library')
    # void bhs_ecs_destroy_entity
    if hasattr(_lib, 'bhs_ecs_destroy_entity'):
        bhs_ecs_destroy_entity = _lib.bhs_ecs_destroy_entity
        bhs_ecs_destroy_entity.argtypes = [ctypes.c_void_p, 'bhs_entity_id']
        bhs_ecs_destroy_entity.restype = None
    else:
        print(f'Warning: Function bhs_ecs_destroy_entity not found in library')
    # void * bhs_ecs_add_component
    if hasattr(_lib, 'bhs_ecs_add_component'):
        bhs_ecs_add_component = _lib.bhs_ecs_add_component
        bhs_ecs_add_component.argtypes = [ctypes.c_void_p, 'bhs_entity_id', 'bhs_component_type', ctypes.c_size_t, ctypes.POINTER('const void')]
        bhs_ecs_add_component.restype = ctypes.c_void_p
    else:
        print(f'Warning: Function bhs_ecs_add_component not found in library')
    # void bhs_ecs_remove_component
    if hasattr(_lib, 'bhs_ecs_remove_component'):
        bhs_ecs_remove_component = _lib.bhs_ecs_remove_component
        bhs_ecs_remove_component.argtypes = [ctypes.c_void_p, 'bhs_entity_id', 'bhs_component_type']
        bhs_ecs_remove_component.restype = None
    else:
        print(f'Warning: Function bhs_ecs_remove_component not found in library')
    # void * bhs_ecs_get_component
    if hasattr(_lib, 'bhs_ecs_get_component'):
        bhs_ecs_get_component = _lib.bhs_ecs_get_component
        bhs_ecs_get_component.argtypes = [ctypes.c_void_p, 'bhs_entity_id', 'bhs_component_type']
        bhs_ecs_get_component.restype = ctypes.c_void_p
    else:
        print(f'Warning: Function bhs_ecs_get_component not found in library')
    # void bhs_ecs_query_init
    if hasattr(_lib, 'bhs_ecs_query_init'):
        bhs_ecs_query_init = _lib.bhs_ecs_query_init
        bhs_ecs_query_init.argtypes = [ctypes.POINTER('bhs_ecs_query'), ctypes.c_void_p, 'bhs_component_mask']
        bhs_ecs_query_init.restype = None
    else:
        print(f'Warning: Function bhs_ecs_query_init not found in library')
    # void bhs_ecs_query_init_cached
    if hasattr(_lib, 'bhs_ecs_query_init_cached'):
        bhs_ecs_query_init_cached = _lib.bhs_ecs_query_init_cached
        bhs_ecs_query_init_cached.argtypes = [ctypes.POINTER('bhs_ecs_query'), ctypes.c_void_p, 'bhs_component_mask']
        bhs_ecs_query_init_cached.restype = None
    else:
        print(f'Warning: Function bhs_ecs_query_init_cached not found in library')
    # bool bhs_ecs_query_next
    if hasattr(_lib, 'bhs_ecs_query_next'):
        bhs_ecs_query_next = _lib.bhs_ecs_query_next
        bhs_ecs_query_next.argtypes = [ctypes.POINTER('bhs_ecs_query'), ctypes.POINTER('bhs_entity_id')]
        bhs_ecs_query_next.restype = ctypes.c_bool
    else:
        print(f'Warning: Function bhs_ecs_query_next not found in library')
    # void bhs_ecs_query_reset
    if hasattr(_lib, 'bhs_ecs_query_reset'):
        bhs_ecs_query_reset = _lib.bhs_ecs_query_reset
        bhs_ecs_query_reset.argtypes = [ctypes.POINTER('bhs_ecs_query')]
        bhs_ecs_query_reset.restype = None
    else:
        print(f'Warning: Function bhs_ecs_query_reset not found in library')
    # void bhs_ecs_query_destroy
    if hasattr(_lib, 'bhs_ecs_query_destroy'):
        bhs_ecs_query_destroy = _lib.bhs_ecs_query_destroy
        bhs_ecs_query_destroy.argtypes = [ctypes.POINTER('bhs_ecs_query')]
        bhs_ecs_query_destroy.restype = None
    else:
        print(f'Warning: Function bhs_ecs_query_destroy not found in library')
    # bool bhs_ecs_entity_has_components
    if hasattr(_lib, 'bhs_ecs_entity_has_components'):
        bhs_ecs_entity_has_components = _lib.bhs_ecs_entity_has_components
        bhs_ecs_entity_has_components.argtypes = [ctypes.c_void_p, 'bhs_entity_id', 'bhs_component_mask']
        bhs_ecs_entity_has_components.restype = ctypes.c_bool
    else:
        print(f'Warning: Function bhs_ecs_entity_has_components not found in library')
    # bool bhs_ecs_save_world
    if hasattr(_lib, 'bhs_ecs_save_world'):
        bhs_ecs_save_world = _lib.bhs_ecs_save_world
        bhs_ecs_save_world.argtypes = [ctypes.c_void_p, ctypes.POINTER('const char')]
        bhs_ecs_save_world.restype = ctypes.c_bool
    else:
        print(f'Warning: Function bhs_ecs_save_world not found in library')
    # bool bhs_ecs_load_world
    if hasattr(_lib, 'bhs_ecs_load_world'):
        bhs_ecs_load_world = _lib.bhs_ecs_load_world
        bhs_ecs_load_world.argtypes = [ctypes.c_void_p, ctypes.POINTER('const char')]
        bhs_ecs_load_world.restype = ctypes.c_bool
    else:
        print(f'Warning: Function bhs_ecs_load_world not found in library')
    # bool bhs_ecs_peek_metadata
    if hasattr(_lib, 'bhs_ecs_peek_metadata'):
        bhs_ecs_peek_metadata = _lib.bhs_ecs_peek_metadata
        bhs_ecs_peek_metadata.argtypes = [ctypes.POINTER('const char'), ctypes.c_void_p, ctypes.c_size_t, ctypes.c_uint32]
        bhs_ecs_peek_metadata.restype = ctypes.c_bool
    else:
        print(f'Warning: Function bhs_ecs_peek_metadata not found in library')
    # bool bhs_ecs_update_metadata
    if hasattr(_lib, 'bhs_ecs_update_metadata'):
        bhs_ecs_update_metadata = _lib.bhs_ecs_update_metadata
        bhs_ecs_update_metadata.argtypes = [ctypes.POINTER('const char'), ctypes.POINTER('const void'), ctypes.c_size_t, ctypes.c_uint32]
        bhs_ecs_update_metadata.restype = ctypes.c_bool
    else:
        print(f'Warning: Function bhs_ecs_update_metadata not found in library')
    # fprint f
    if hasattr(_lib, 'f'):
        f = _lib.f
        f.argtypes = ['stderr', '"', '__FILE__', '__LINE__', '\']
        f.restype = 'fprint'
    else:
        print(f'Warning: Function f not found in library')
    # abor t
    if hasattr(_lib, 't'):
        t = _lib.t
        t.argtypes = []
        t.restype = 'abor'
    else:
        print(f'Warning: Function t not found in library')
    # fprint f
    if hasattr(_lib, 'f'):
        f = _lib.f
        f.argtypes = ['stderr', '"', '\', '__LINE__']
        f.restype = 'fprint'
    else:
        print(f'Warning: Function f not found in library')
    # abor t
    if hasattr(_lib, 't'):
        t = _lib.t
        t.argtypes = []
        t.restype = 'abor'
    else:
        print(f'Warning: Function t not found in library')
    # bhs_metric bhs_metric_zero
    if hasattr(_lib, 'bhs_metric_zero'):
        bhs_metric_zero = _lib.bhs_metric_zero
        bhs_metric_zero.argtypes = []
        bhs_metric_zero.restype = 'bhs_metric'
    else:
        print(f'Warning: Function bhs_metric_zero not found in library')
    # bhs_metric bhs_metric_minkowski
    if hasattr(_lib, 'bhs_metric_minkowski'):
        bhs_metric_minkowski = _lib.bhs_metric_minkowski
        bhs_metric_minkowski.argtypes = []
        bhs_metric_minkowski.restype = 'bhs_metric'
    else:
        print(f'Warning: Function bhs_metric_minkowski not found in library')
    # bhs_metric bhs_metric_diag
    if hasattr(_lib, 'bhs_metric_diag'):
        bhs_metric_diag = _lib.bhs_metric_diag
        bhs_metric_diag.argtypes = [ctypes.c_double, ctypes.c_double, ctypes.c_double, ctypes.c_double]
        bhs_metric_diag.restype = 'bhs_metric'
    else:
        print(f'Warning: Function bhs_metric_diag not found in library')
    # bool bhs_metric_is_symmetric
    if hasattr(_lib, 'bhs_metric_is_symmetric'):
        bhs_metric_is_symmetric = _lib.bhs_metric_is_symmetric
        bhs_metric_is_symmetric.argtypes = [ctypes.POINTER('const struct bhs_metric'), ctypes.c_double]
        bhs_metric_is_symmetric.restype = ctypes.c_bool
    else:
        print(f'Warning: Function bhs_metric_is_symmetric not found in library')
    # real_t bhs_metric_det
    if hasattr(_lib, 'bhs_metric_det'):
        bhs_metric_det = _lib.bhs_metric_det
        bhs_metric_det.argtypes = [ctypes.POINTER('const struct bhs_metric')]
        bhs_metric_det.restype = ctypes.c_double
    else:
        print(f'Warning: Function bhs_metric_det not found in library')
    # int bhs_metric_invert
    if hasattr(_lib, 'bhs_metric_invert'):
        bhs_metric_invert = _lib.bhs_metric_invert
        bhs_metric_invert.argtypes = [ctypes.POINTER('const struct bhs_metric'), ctypes.POINTER(bhs_metric)]
        bhs_metric_invert.restype = ctypes.c_int
    else:
        print(f'Warning: Function bhs_metric_invert not found in library')
    # bhs_vec4 bhs_metric_lower
    if hasattr(_lib, 'bhs_metric_lower'):
        bhs_metric_lower = _lib.bhs_metric_lower
        bhs_metric_lower.argtypes = [ctypes.POINTER('const struct bhs_metric'), bhs_vec4]
        bhs_metric_lower.restype = 'bhs_vec4'
    else:
        print(f'Warning: Function bhs_metric_lower not found in library')
    # bhs_vec4 bhs_metric_raise
    if hasattr(_lib, 'bhs_metric_raise'):
        bhs_metric_raise = _lib.bhs_metric_raise
        bhs_metric_raise.argtypes = [ctypes.POINTER('const struct bhs_metric'), bhs_vec4]
        bhs_metric_raise.restype = 'bhs_vec4'
    else:
        print(f'Warning: Function bhs_metric_raise not found in library')
    # real_t bhs_metric_dot
    if hasattr(_lib, 'bhs_metric_dot'):
        bhs_metric_dot = _lib.bhs_metric_dot
        bhs_metric_dot.argtypes = [ctypes.POINTER('const struct bhs_metric'), bhs_vec4, bhs_vec4]
        bhs_metric_dot.restype = ctypes.c_double
    else:
        print(f'Warning: Function bhs_metric_dot not found in library')
    # int bhs_christoffel_compute
    if hasattr(_lib, 'bhs_christoffel_compute'):
        bhs_christoffel_compute = _lib.bhs_christoffel_compute
        bhs_christoffel_compute.argtypes = ['bhs_metric_func', bhs_vec4, ctypes.c_void_p, ctypes.c_double, ctypes.POINTER(bhs_christoffel)]
        bhs_christoffel_compute.restype = ctypes.c_int
    else:
        print(f'Warning: Function bhs_christoffel_compute not found in library')
    # bhs_christoffel bhs_christoffel_zero
    if hasattr(_lib, 'bhs_christoffel_zero'):
        bhs_christoffel_zero = _lib.bhs_christoffel_zero
        bhs_christoffel_zero.argtypes = []
        bhs_christoffel_zero.restype = 'bhs_christoffel'
    else:
        print(f'Warning: Function bhs_christoffel_zero not found in library')
    # bhs_vec4 bhs_geodesic_accel
    if hasattr(_lib, 'bhs_geodesic_accel'):
        bhs_geodesic_accel = _lib.bhs_geodesic_accel
        bhs_geodesic_accel.argtypes = [ctypes.POINTER('const struct bhs_christoffel'), bhs_vec4]
        bhs_geodesic_accel.restype = 'bhs_vec4'
    else:
        print(f'Warning: Function bhs_geodesic_accel not found in library')
    # co s
    if hasattr(_lib, 's'):
        s = _lib.s
        s.argtypes = ['theta']
        s.restype = 'co'
    else:
        print(f'Warning: Function s not found in library')
    # double bhs_kerr_horizon_outer
    if hasattr(_lib, 'bhs_kerr_horizon_outer'):
        bhs_kerr_horizon_outer = _lib.bhs_kerr_horizon_outer
        bhs_kerr_horizon_outer.argtypes = [ctypes.POINTER('const struct bhs_kerr')]
        bhs_kerr_horizon_outer.restype = ctypes.c_double
    else:
        print(f'Warning: Function bhs_kerr_horizon_outer not found in library')
    # double bhs_kerr_horizon_inner
    if hasattr(_lib, 'bhs_kerr_horizon_inner'):
        bhs_kerr_horizon_inner = _lib.bhs_kerr_horizon_inner
        bhs_kerr_horizon_inner.argtypes = [ctypes.POINTER('const struct bhs_kerr')]
        bhs_kerr_horizon_inner.restype = ctypes.c_double
    else:
        print(f'Warning: Function bhs_kerr_horizon_inner not found in library')
    # double bhs_kerr_ergosphere
    if hasattr(_lib, 'bhs_kerr_ergosphere'):
        bhs_kerr_ergosphere = _lib.bhs_kerr_ergosphere
        bhs_kerr_ergosphere.argtypes = [ctypes.POINTER('const struct bhs_kerr'), ctypes.c_double]
        bhs_kerr_ergosphere.restype = ctypes.c_double
    else:
        print(f'Warning: Function bhs_kerr_ergosphere not found in library')
    # double bhs_kerr_isco
    if hasattr(_lib, 'bhs_kerr_isco'):
        bhs_kerr_isco = _lib.bhs_kerr_isco
        bhs_kerr_isco.argtypes = [ctypes.POINTER('const struct bhs_kerr'), ctypes.c_bool]
        bhs_kerr_isco.restype = ctypes.c_double
    else:
        print(f'Warning: Function bhs_kerr_isco not found in library')
    # double bhs_kerr_omega_frame
    if hasattr(_lib, 'bhs_kerr_omega_frame'):
        bhs_kerr_omega_frame = _lib.bhs_kerr_omega_frame
        bhs_kerr_omega_frame.argtypes = [ctypes.POINTER('const struct bhs_kerr'), ctypes.c_double, ctypes.c_double]
        bhs_kerr_omega_frame.restype = ctypes.c_double
    else:
        print(f'Warning: Function bhs_kerr_omega_frame not found in library')
    # void bhs_kerr_metric
    if hasattr(_lib, 'bhs_kerr_metric'):
        bhs_kerr_metric = _lib.bhs_kerr_metric
        bhs_kerr_metric.argtypes = [ctypes.POINTER('const struct bhs_kerr'), ctypes.c_double, ctypes.c_double, ctypes.POINTER(bhs_metric)]
        bhs_kerr_metric.restype = None
    else:
        print(f'Warning: Function bhs_kerr_metric not found in library')
    # void bhs_kerr_metric_inverse
    if hasattr(_lib, 'bhs_kerr_metric_inverse'):
        bhs_kerr_metric_inverse = _lib.bhs_kerr_metric_inverse
        bhs_kerr_metric_inverse.argtypes = [ctypes.POINTER('const struct bhs_kerr'), ctypes.c_double, ctypes.c_double, ctypes.POINTER(bhs_metric)]
        bhs_kerr_metric_inverse.restype = None
    else:
        print(f'Warning: Function bhs_kerr_metric_inverse not found in library')
    # double bhs_kerr_redshift_zamo
    if hasattr(_lib, 'bhs_kerr_redshift_zamo'):
        bhs_kerr_redshift_zamo = _lib.bhs_kerr_redshift_zamo
        bhs_kerr_redshift_zamo.argtypes = [ctypes.POINTER('const struct bhs_kerr'), ctypes.c_double, ctypes.c_double]
        bhs_kerr_redshift_zamo.restype = ctypes.c_double
    else:
        print(f'Warning: Function bhs_kerr_redshift_zamo not found in library')
    # void bhs_kerr_metric_func
    if hasattr(_lib, 'bhs_kerr_metric_func'):
        bhs_kerr_metric_func = _lib.bhs_kerr_metric_func
        bhs_kerr_metric_func.argtypes = [bhs_vec4, ctypes.c_void_p, ctypes.POINTER(bhs_metric)]
        bhs_kerr_metric_func.restype = None
    else:
        print(f'Warning: Function bhs_kerr_metric_func not found in library')
    # void bhs_schwarzschild_metric
    if hasattr(_lib, 'bhs_schwarzschild_metric'):
        bhs_schwarzschild_metric = _lib.bhs_schwarzschild_metric
        bhs_schwarzschild_metric.argtypes = [ctypes.POINTER('const struct bhs_schwarzschild'), ctypes.c_double, ctypes.c_double, ctypes.POINTER(bhs_metric)]
        bhs_schwarzschild_metric.restype = None
    else:
        print(f'Warning: Function bhs_schwarzschild_metric not found in library')
    # void bhs_schwarzschild_metric_inverse
    if hasattr(_lib, 'bhs_schwarzschild_metric_inverse'):
        bhs_schwarzschild_metric_inverse = _lib.bhs_schwarzschild_metric_inverse
        bhs_schwarzschild_metric_inverse.argtypes = [ctypes.POINTER('const struct bhs_schwarzschild'), ctypes.c_double, ctypes.c_double, ctypes.POINTER(bhs_metric)]
        bhs_schwarzschild_metric_inverse.restype = None
    else:
        print(f'Warning: Function bhs_schwarzschild_metric_inverse not found in library')
    # double bhs_schwarzschild_redshift
    if hasattr(_lib, 'bhs_schwarzschild_redshift'):
        bhs_schwarzschild_redshift = _lib.bhs_schwarzschild_redshift
        bhs_schwarzschild_redshift.argtypes = [ctypes.POINTER('const struct bhs_schwarzschild'), ctypes.c_double]
        bhs_schwarzschild_redshift.restype = ctypes.c_double
    else:
        print(f'Warning: Function bhs_schwarzschild_redshift not found in library')
    # double bhs_schwarzschild_escape_velocity
    if hasattr(_lib, 'bhs_schwarzschild_escape_velocity'):
        bhs_schwarzschild_escape_velocity = _lib.bhs_schwarzschild_escape_velocity
        bhs_schwarzschild_escape_velocity.argtypes = [ctypes.POINTER('const struct bhs_schwarzschild'), ctypes.c_double]
        bhs_schwarzschild_escape_velocity.restype = ctypes.c_double
    else:
        print(f'Warning: Function bhs_schwarzschild_escape_velocity not found in library')
    # void bhs_schwarzschild_metric_func
    if hasattr(_lib, 'bhs_schwarzschild_metric_func'):
        bhs_schwarzschild_metric_func = _lib.bhs_schwarzschild_metric_func
        bhs_schwarzschild_metric_func.argtypes = [bhs_vec4, ctypes.c_void_p, ctypes.POINTER(bhs_metric)]
        bhs_schwarzschild_metric_func.restype = None
    else:
        print(f'Warning: Function bhs_schwarzschild_metric_func not found in library')
    # void bhs_engine_init
    if hasattr(_lib, 'bhs_engine_init'):
        bhs_engine_init = _lib.bhs_engine_init
        bhs_engine_init.argtypes = []
        bhs_engine_init.restype = None
    else:
        print(f'Warning: Function bhs_engine_init not found in library')
    # void bhs_engine_shutdown
    if hasattr(_lib, 'bhs_engine_shutdown'):
        bhs_engine_shutdown = _lib.bhs_engine_shutdown
        bhs_engine_shutdown.argtypes = []
        bhs_engine_shutdown.restype = None
    else:
        print(f'Warning: Function bhs_engine_shutdown not found in library')
    # void bhs_engine_update
    if hasattr(_lib, 'bhs_engine_update'):
        bhs_engine_update = _lib.bhs_engine_update
        bhs_engine_update.argtypes = [ctypes.c_double]
        bhs_engine_update.restype = None
    else:
        print(f'Warning: Function bhs_engine_update not found in library')
    # void bhs_scene_load
    if hasattr(_lib, 'bhs_scene_load'):
        bhs_scene_load = _lib.bhs_scene_load
        bhs_scene_load.argtypes = [ctypes.POINTER('const char')]
        bhs_scene_load.restype = None
    else:
        print(f'Warning: Function bhs_scene_load not found in library')
    # bhs_scene_t bhs_scene_create
    if hasattr(_lib, 'bhs_scene_create'):
        bhs_scene_create = _lib.bhs_scene_create
        bhs_scene_create.argtypes = []
        bhs_scene_create.restype = ctypes.c_void_p
    else:
        print(f'Warning: Function bhs_scene_create not found in library')
    # void bhs_scene_destroy
    if hasattr(_lib, 'bhs_scene_destroy'):
        bhs_scene_destroy = _lib.bhs_scene_destroy
        bhs_scene_destroy.argtypes = [ctypes.c_void_p]
        bhs_scene_destroy.restype = None
    else:
        print(f'Warning: Function bhs_scene_destroy not found in library')
    # void bhs_scene_init_default
    if hasattr(_lib, 'bhs_scene_init_default'):
        bhs_scene_init_default = _lib.bhs_scene_init_default
        bhs_scene_init_default.argtypes = [ctypes.c_void_p]
        bhs_scene_init_default.restype = None
    else:
        print(f'Warning: Function bhs_scene_init_default not found in library')
    # void bhs_scene_update
    if hasattr(_lib, 'bhs_scene_update'):
        bhs_scene_update = _lib.bhs_scene_update
        bhs_scene_update.argtypes = [ctypes.c_void_p, ctypes.c_double]
        bhs_scene_update.restype = None
    else:
        print(f'Warning: Function bhs_scene_update not found in library')
    # bhs_world_handle bhs_scene_get_world
    if hasattr(_lib, 'bhs_scene_get_world'):
        bhs_scene_get_world = _lib.bhs_scene_get_world
        bhs_scene_get_world.argtypes = [ctypes.c_void_p]
        bhs_scene_get_world.restype = ctypes.c_void_p
    else:
        print(f'Warning: Function bhs_scene_get_world not found in library')
    # bhs_body * bhs_scene_get_bodies
    if hasattr(_lib, 'bhs_scene_get_bodies'):
        bhs_scene_get_bodies = _lib.bhs_scene_get_bodies
        bhs_scene_get_bodies.argtypes = [ctypes.c_void_p, ctypes.POINTER(ctypes.c_int)]
        bhs_scene_get_bodies.restype = ctypes.POINTER('bhs_body')
    else:
        print(f'Warning: Function bhs_scene_get_bodies not found in library')
    # bhs_entity_id bhs_scene_add_body_struct
    if hasattr(_lib, 'bhs_scene_add_body_struct'):
        bhs_scene_add_body_struct = _lib.bhs_scene_add_body_struct
        bhs_scene_add_body_struct.argtypes = [ctypes.c_void_p, bhs_body]
        bhs_scene_add_body_struct.restype = 'bhs_entity_id'
    else:
        print(f'Warning: Function bhs_scene_add_body_struct not found in library')
    # bhs_entity_id bhs_scene_add_body
    if hasattr(_lib, 'bhs_scene_add_body'):
        bhs_scene_add_body = _lib.bhs_scene_add_body
        bhs_scene_add_body.argtypes = [ctypes.c_void_p, ctypes.c_int, bhs_vec3, bhs_vec3, ctypes.c_double, ctypes.c_double, bhs_vec3]
        bhs_scene_add_body.restype = 'bhs_entity_id'
    else:
        print(f'Warning: Function bhs_scene_add_body not found in library')
    # bhs_entity_id bhs_scene_add_body_named
    if hasattr(_lib, 'bhs_scene_add_body_named'):
        bhs_scene_add_body_named = _lib.bhs_scene_add_body_named
        bhs_scene_add_body_named.argtypes = [ctypes.c_void_p, ctypes.c_int, bhs_vec3, bhs_vec3, ctypes.c_double, ctypes.c_double, bhs_vec3, ctypes.POINTER('const char')]
        bhs_scene_add_body_named.restype = 'bhs_entity_id'
    else:
        print(f'Warning: Function bhs_scene_add_body_named not found in library')
    # void bhs_scene_remove_body
    if hasattr(_lib, 'bhs_scene_remove_body'):
        bhs_scene_remove_body = _lib.bhs_scene_remove_body
        bhs_scene_remove_body.argtypes = [ctypes.c_void_p, ctypes.c_int]
        bhs_scene_remove_body.restype = None
    else:
        print(f'Warning: Function bhs_scene_remove_body not found in library')
    # void bhs_scene_reset_counters
    if hasattr(_lib, 'bhs_scene_reset_counters'):
        bhs_scene_reset_counters = _lib.bhs_scene_reset_counters
        bhs_scene_reset_counters.argtypes = []
        bhs_scene_reset_counters.restype = None
    else:
        print(f'Warning: Function bhs_scene_reset_counters not found in library')
    # bhs_body bhs_body_create_planet_simple
    if hasattr(_lib, 'bhs_body_create_planet_simple'):
        bhs_body_create_planet_simple = _lib.bhs_body_create_planet_simple
        bhs_body_create_planet_simple.argtypes = [bhs_vec3, ctypes.c_double, ctypes.c_double, bhs_vec3]
        bhs_body_create_planet_simple.restype = 'bhs_body'
    else:
        print(f'Warning: Function bhs_body_create_planet_simple not found in library')
    # bhs_body bhs_body_create_star_simple
    if hasattr(_lib, 'bhs_body_create_star_simple'):
        bhs_body_create_star_simple = _lib.bhs_body_create_star_simple
        bhs_body_create_star_simple.argtypes = [bhs_vec3, ctypes.c_double, ctypes.c_double, bhs_vec3]
        bhs_body_create_star_simple.restype = 'bhs_body'
    else:
        print(f'Warning: Function bhs_body_create_star_simple not found in library')
    # bhs_body bhs_body_create_blackhole_simple
    if hasattr(_lib, 'bhs_body_create_blackhole_simple'):
        bhs_body_create_blackhole_simple = _lib.bhs_body_create_blackhole_simple
        bhs_body_create_blackhole_simple.argtypes = [bhs_vec3, ctypes.c_double, ctypes.c_double]
        bhs_body_create_blackhole_simple.restype = 'bhs_body'
    else:
        print(f'Warning: Function bhs_body_create_blackhole_simple not found in library')
    # bhs_body bhs_body_create_from_desc
    if hasattr(_lib, 'bhs_body_create_from_desc'):
        bhs_body_create_from_desc = _lib.bhs_body_create_from_desc
        bhs_body_create_from_desc.argtypes = [ctypes.POINTER('const struct bhs_planet_desc'), bhs_vec3]
        bhs_body_create_from_desc.restype = 'bhs_body'
    else:
        print(f'Warning: Function bhs_body_create_from_desc not found in library')
    # bhs_body bhs_body_create_from_sun_desc
    if hasattr(_lib, 'bhs_body_create_from_sun_desc'):
        bhs_body_create_from_sun_desc = _lib.bhs_body_create_from_sun_desc
        bhs_body_create_from_sun_desc.argtypes = [ctypes.POINTER('const struct bhs_sun_desc'), bhs_vec3]
        bhs_body_create_from_sun_desc.restype = 'bhs_body'
    else:
        print(f'Warning: Function bhs_body_create_from_sun_desc not found in library')
    # bhs_body bhs_body_create_from_bh_desc
    if hasattr(_lib, 'bhs_body_create_from_bh_desc'):
        bhs_body_create_from_bh_desc = _lib.bhs_body_create_from_bh_desc
        bhs_body_create_from_bh_desc.argtypes = [ctypes.POINTER('const struct bhs_blackhole_desc'), bhs_vec3]
        bhs_body_create_from_bh_desc.restype = 'bhs_body'
    else:
        print(f'Warning: Function bhs_body_create_from_bh_desc not found in library')
